"""
Deterministic FHIR-like JSON parser → structured clinical context.
Zero external deps, works on plain dict bundles (generated by data/generator.py).
"""
from __future__ import annotations
import json
from datetime import datetime
from pathlib import Path
from typing import Any
from collections import defaultdict

LOINC_MAP = {
    "4548-4": "hba1c", "1558-6": "fasting_glucose",
    "8480-6": "bp_systolic", "8462-4": "bp_diastolic",
    "2160-0": "creatinine", "33914-3": "egfr", "2823-3": "potassium",
    "29463-7": "weight", "718-7": "hb", "8281-8": "muac",
    "1742-6": "alt", "1920-8": "ast", "1975-2": "bilirubin",
    "2888-6": "proteinuria", "8302-2": "height",
    "637-4": "sputum_afb",
}

THRESHOLDS = {
    "hba1c": {"critical": 9.0, "warning": 7.5, "unit": "%"},
    "fasting_glucose": {"critical": 180, "warning": 130, "unit": "mg/dL"},
    "bp_systolic": {"critical": 160, "warning": 140, "unit": "mmHg"},
    "bp_diastolic": {"critical": 100, "warning": 90, "unit": "mmHg"},
    "creatinine": {"critical": 1.5, "warning": 1.2, "unit": "mg/dL"},
    "egfr": {"critical": 30, "warning": 45, "unit": "mL/min", "reverse": True},
    "potassium": {"critical": 5.5, "warning": 5.0, "unit": "mmol/L"},
    "hb": {"critical": 8.0, "warning": 10.0, "unit": "g/dL", "reverse": True},
    "muac": {"critical": 115, "warning": 125, "unit": "mm", "reverse": True},
}


class FHIRParser:
    def __init__(self, bundle: dict[str, Any]):
        self.bundle = bundle
        self.patient: dict = {}
        self.conditions: list[dict] = []
        self.medications: list[dict] = []
        self.observations: dict[str, list[dict]] = defaultdict(list)
        self.encounters: list[dict] = []
        self._medications: dict[str, dict] = {}
        self._parse()

    def _parse(self):
        for entry in self.bundle.get("entry", []):
            res = entry.get("resource", {})
            rtype = res.get("resourceType")
            if rtype == "Patient":
                self.patient = res
            elif rtype == "Condition":
                self.conditions.append(res)
            elif rtype == "Medication":
                self._medications[res.get("id")] = res
            elif rtype == "MedicationRequest":
                self.medications.append(res)
            elif rtype == "Observation":
                self._parse_obs(res)
            elif rtype == "Encounter":
                self.encounters.append(res)

    def _parse_obs(self, obs: dict):
        coding = obs.get("code", {}).get("coding", [])
        for c in coding:
            if c.get("code") in LOINC_MAP:
                self.observations[LOINC_MAP[c["code"]]].append(obs)
                return

    def _resolve_med_name(self, mr: dict) -> str:
        ref = mr.get("medicationReference", {}).get("reference", "")
        if not ref:
            ref = mr.get("medication", {}).get("reference", {}).get("reference", "")
        if ref.startswith("Medication/"):
            med = self._medications.get(ref.split("/")[-1])
            if med and med.get("code", {}).get("coding"):
                return med["code"]["coding"][0].get("display", "Unknown")
        return "Unknown"

    def _calculate_age(self) -> int:
        dob = self.patient.get("birthDate", "")
        if not dob:
            return 0
        try:
            birth = datetime.fromisoformat(dob[:10]).date()
            today = datetime.now().date()
            return today.year - birth.year - ((today.month, today.day) < (birth.month, birth.day))
        except:
            return 0

    def get_patient_summary(self) -> dict[str, Any]:
        name = ""
        if self.patient.get("name"):
            n = self.patient["name"][0]
            name = f"{' '.join(n.get('given', []))} {n.get('family', '')}".strip()
        return {
            "age": self._calculate_age(),
            "gender": "M" if self.patient.get("gender") == "male" else "F",
            "name": name,
            "patient_id": self.patient.get("id", "?"),
        }

    def get_active_problems(self) -> list[dict[str, Any]]:
        problems = []
        for cond in self.conditions:
            status = cond.get("clinicalStatus", {}).get("coding", [{}])[0].get("code", "")
            if status in ("active", "recurrence", "relapse"):
                code = cond.get("code", {}).get("coding", [{}])[0]
                problems.append({
                    "code": code.get("code"),
                    "display": code.get("display", "Unknown"),
                })
        return problems

    def get_current_medications(self) -> list[dict[str, Any]]:
        meds = []
        for mr in self.medications:
            if mr.get("status") in ("active", "on-hold"):
                dose = ""
                if mr.get("dosageInstruction"):
                    dose = mr["dosageInstruction"][0].get("text", "")
                meds.append({
                    "name": self._resolve_med_name(mr),
                    "dose": dose,
                    "status": mr.get("status"),
                })
        return meds

    def get_latest_vitals(self) -> dict[str, dict]:
        vitals = {}
        for key, obs_list in self.observations.items():
            if not obs_list:
                continue
            sorted_obs = sorted(
                obs_list,
                key=lambda o: o.get("effectiveDateTime", "1970-01-01"),
                reverse=True,
            )
            latest = sorted_obs[0]
            vq = latest.get("valueQuantity", {})
            vals = [o.get("valueQuantity", {}).get("value", 0) for o in sorted_obs[:3] if o.get("valueQuantity")]
            trend = "stable"
            if len(vals) >= 3:
                if vals[0] >= vals[1] >= vals[2]:
                    trend = "falling"
                elif vals[0] <= vals[1] <= vals[2]:
                    trend = "rising"
            vitals[key] = {
                "value": vq.get("value"),
                "unit": vq.get("unit"),
                "date": latest.get("effectiveDateTime"),
                "trend": trend,
            }
        return vitals

    def get_red_flags(self) -> list[dict]:
        flags = []
        vitals = self.get_latest_vitals()
        meds = [m["name"].lower() for m in self.get_current_medications()]

        for key, th in THRESHOLDS.items():
            if key not in vitals:
                continue
            val = vitals[key].get("value")
            if val is None:
                continue
            rev = th.get("reverse", False)
            crit = th.get("critical")
            warn = th.get("warning")
            if crit is not None:
                if (not rev and val >= crit) or (rev and val <= crit):
                    flags.append({"type": "critical", "key": key, "value": val, "unit": th["unit"], "threshold": crit, "message": f"{key.replace('_',' ').title()} {val} {th['unit']} (threshold {crit})"})
                elif warn is not None and ((not rev and val >= warn) or (rev and val <= warn)):
                    flags.append({"type": "warning", "key": key, "value": val, "unit": th["unit"], "threshold": warn, "message": f"{key.replace('_',' ').title()} {val} {th['unit']} (threshold {warn})"})

        if self.encounters:
            last = max(self.encounters, key=lambda e: e.get("period", {}).get("start", "1970-01-01"))
            start = last.get("period", {}).get("start", "")
            if start:
                days = (datetime.now() - datetime.fromisoformat(start[:10])).days
                if days > 90:
                    flags.append({"type": "warning", "key": "missed_followup", "value": days, "unit": "days", "threshold": 90, "message": f"No visit in {days}d"})

        return flags

    def get_missing_data(self) -> list[str]:
        problems = [p["display"].lower() for p in self.get_active_problems()]
        vitals = self.get_latest_vitals()
        missing = []
        if any("diabetes" in p for p in problems):
            if "hba1c" not in vitals:
                missing.append("HbA1c")
        if any("hypertens" in p for p in problems):
            if "bp_systolic" not in vitals:
                missing.append("Blood Pressure")
        if any("tuberculosis" in p for p in problems):
            if "weight" not in vitals:
                missing.append("Weight trend")
        return missing

    def get_chronic_snapshot(self) -> dict[str, Any]:
        snap = {}
        vitals = self.get_latest_vitals()
        problems = [p["display"].lower() for p in self.get_active_problems()]
        if any("diabetes" in p for p in problems) and "hba1c" in vitals:
            v = vitals["hba1c"]
            snap["diabetes"] = {"last_hba1c": f"{v.get('value','?')} {v.get('unit','%')}", "trend": v.get("trend","unknown"), "control": "uncontrolled" if v.get("value",0) >= 7.5 else "controlled"}
        if any("hypertens" in p for p in problems) and "bp_systolic" in vitals:
            sys = vitals["bp_systolic"]
            dia = vitals.get("bp_diastolic", {})
            snap["hypertension"] = {"last_bp": f"{sys.get('value','?')}/{dia.get('value','?')} mmHg", "trend": sys.get("trend","unknown"), "control": "uncontrolled" if sys.get("value",0) >= 140 else "controlled"}
        return snap

    def get_day_timeline(self) -> list[dict[str, Any]]:
        """Extract day-by-day clinical timeline from FHIR bundle."""
        days: dict[str, dict] = defaultdict(lambda: {
            "date": "",
            "encounters": [],
            "vitals": [],
            "medications_started": [],
            "conditions_diagnosed": [],
            "labs": [],
        })

        for enc in self.encounters:
            period = enc.get("period", {})
            start = period.get("start", "")
            if start:
                day_key = start[:10]
                days[day_key]["date"] = day_key
                days[day_key]["encounters"].append({
                    "type": enc.get("type", [{}])[0].get("coding", [{}])[0].get("display", "Visit"),
                    "provider": enc.get("participant", [{}])[0].get("individual", {}).get("display", "Unknown"),
                    "status": enc.get("status", "unknown"),
                })

        for key, obs_list in self.observations.items():
            for obs in obs_list:
                dt = obs.get("effectiveDateTime", "")
                if dt:
                    day_key = dt[:10]
                    days[day_key]["date"] = day_key
                    vq = obs.get("valueQuantity", {})
                    display_name = obs.get("code", {}).get("coding", [{}])[0].get("display", key)
                    entry = {
                        "type": key,
                        "display": display_name,
                        "value": vq.get("value"),
                        "unit": vq.get("unit"),
                        "datetime": dt,
                    }
                    if key in ["hba1c", "fasting_glucose", "creatinine", "egfr", "potassium", "hb", "muac", "alt", "ast", "bilirubin", "proteinuria"]:
                        days[day_key]["labs"].append(entry)
                    else:
                        days[day_key]["vitals"].append(entry)

        for mr in self.medications:
            authored = mr.get("authoredOn", "")
            if authored:
                day_key = authored[:10]
                days[day_key]["date"] = day_key
                days[day_key]["medications_started"].append({
                    "name": self._resolve_med_name(mr),
                    "dose": mr.get("dosageInstruction", [{}])[0].get("text", ""),
                    "status": mr.get("status"),
                })

        for cond in self.conditions:
            onset = cond.get("onsetDateTime", "") or cond.get("recordedDate", "")
            if onset:
                day_key = onset[:10]
                days[day_key]["date"] = day_key
                code = cond.get("code", {}).get("coding", [{}])[0]
                days[day_key]["conditions_diagnosed"].append({
                    "code": code.get("code"),
                    "display": code.get("display", "Unknown"),
                    "status": cond.get("clinicalStatus", {}).get("coding", [{}])[0].get("code", "active"),
                })

        sorted_days = sorted(days.items(), key=lambda x: x[0], reverse=True)
        return [day_data for _, day_data in sorted_days if day_data["date"]]

    def extract_all(self) -> dict[str, Any]:
        return {
            "patient": self.get_patient_summary(),
            "active_problems": self.get_active_problems(),
            "medications": self.get_current_medications(),
            "vitals": self.get_latest_vitals(),
            "red_flags": self.get_red_flags(),
            "missing_data": self.get_missing_data(),
            "chronic_snapshot": self.get_chronic_snapshot(),
            "encounter_count": len(self.encounters),
            "day_timeline": self.get_day_timeline(),
        }


def parse_fhir_bundle(filepath: str | Path) -> dict[str, Any]:
    with open(filepath) as f:
        return FHIRParser(json.load(f)).extract_all()


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        ctx = parse_fhir_bundle(sys.argv[1])
        print(json.dumps(ctx, indent=2, default=str))