import { NextResponse } from 'next/server';

export async function GET() {
  const symptoms = [
    { icd11: "MG44", display: "Fever", category: "General" },
    { icd11: "MD11", display: "Cough", category: "Respiratory" },
    { icd11: "MD12", display: "Shortness of breath", category: "Respiratory" },
    { icd11: "MD15", display: "Hemoptysis", category: "Respiratory" },
    { icd11: "MB23", display: "Weight loss", category: "General" },
    { icd11: "MG40", display: "Fatigue/Weakness", category: "General" },
    { icd11: "ME00", display: "Abdominal pain", category: "Gastrointestinal" },
    { icd11: "ME01", display: "Diarrhea", category: "Gastrointestinal" },
    { icd11: "ME02", display: "Vomiting", category: "Gastrointestinal" },
    { icd11: "ME04", display: "Constipation", category: "Gastrointestinal" },
    { icd11: "MB01", display: "Edema/Swelling", category: "Cardiovascular" },
    { icd11: "MB40", display: "Headache", category: "Neurological" },
    { icd11: "MB41", display: "Dizziness", category: "Neurological" },
    { icd11: "MB42", display: "Seizure", category: "Neurological" },
    { icd11: "MB43", display: "Chest pain", category: "Cardiovascular" },
    { icd11: "MB44", display: "Palpitations", category: "Cardiovascular" },
    { icd11: "MB50", display: "Joint pain", category: "Musculoskeletal" },
    { icd11: "MB51", display: "Back pain", category: "Musculoskeletal" },
    { icd11: "MF40", display: "Skin rash", category: "Dermatological" },
    { icd11: "MF41", display: "Pruritus (Itching)", category: "Dermatological" },
    { icd11: "MF42", display: "Hair loss", category: "Dermatological" },
    { icd11: "MC70", display: "Sore throat", category: "ENT" },
    { icd11: "MC71", display: "Ear pain", category: "ENT" },
    { icd11: "MC72", display: "Nasal discharge", category: "ENT" },
    { icd11: "MC73", display: "Hearing loss", category: "ENT" },
    { icd11: "MB20", display: "Anorexia", category: "Gastrointestinal" },
    { icd11: "MB21", display: "Nausea", category: "Gastrointestinal" },
    { icd11: "MF10", display: "Insomnia", category: "Psychiatric" },
    { icd11: "MF11", display: "Anxiety", category: "Psychiatric" },
    { icd11: "MF12", display: "Depression", category: "Psychiatric" },
    { icd11: "GA01", display: "Vaginal bleeding", category: "Obstetric" },
    { icd11: "GA02", display: "Morning sickness", category: "Obstetric" },
    { icd11: "GA03", display: "Fetal movement reduced", category: "Obstetric" },
    { icd11: "KB00", display: "Poor feeding", category: "Pediatric" },
    { icd11: "KB01", display: "Irritability", category: "Pediatric" },
    { icd11: "KB02", display: "Failure to thrive", category: "Pediatric" },
    { icd11: "KB03", display: "Convulsions", category: "Pediatric" },
    { icd11: "MB45", display: "Syncope", category: "Cardiovascular" },
    { icd11: "MB46", display: "Tremor", category: "Neurological" },
    { icd11: "MD20", display: "Wheezing", category: "Respiratory" },
    { icd11: "MD21", display: "Chest tightness", category: "Respiratory" },
    { icd11: "ME10", display: "Dysphagia", category: "Gastrointestinal" },
    { icd11: "ME11", display: "Heartburn", category: "Gastrointestinal" },
    { icd11: "ME12", display: "Jaundice", category: "Hepatobiliary" },
    { icd11: "ME13", display: "Ascites", category: "Hepatobiliary" },
    { icd11: "ME20", display: "Dysuria", category: "Renal" },
    { icd11: "ME21", display: "Hematuria", category: "Renal" },
    { icd11: "ME22", display: "Frequency/Nocturia", category: "Renal" },
    { icd11: "MF20", display: "Blurred vision", category: "Ophthalmological" },
    { icd11: "MF21", display: "Eye pain", category: "Ophthalmological" },
    { icd11: "MF22", display: "Red eye", category: "Ophthalmological" }
  ];

  return NextResponse.json({ symptoms });
}
